### ISSUE TITLE
deployVerticle does not support multiple calls adding classpaths

### ISSUE THREAD

**Issue by msillence** [vert-x3/vertx-service-factory#11]
### Version

    vert.x core: 3.7.1
    vert.x web: N/A

### Context

I was trying to add something that will load all our jar files and start them up ideally with class loading isolation.

The deployVerticle sounds perfect but after loading the first module the second fails to load. it seems to only use the DeploymentOptions.extraClasspath from the first instance
Do you have a reproducer?

https://github.com/msillence/vertx-start-test/tree/master
Steps to reproduce

    run mvn pacage at the root
    run the main class jhc.vertx.StartServices from within that module

The second deployment fails

### Extra

Commenting out the two start calls and commenting the single startCombinedClassPath will work

My actual plan was to verify behaviour of class loading separation when I found a more fundamental problem.

Following further investigation I found it only fails when we use the "service:" notation to load the json file, it works fine and the class isolation also works when you specify the class instead
I presume that it's correctly using the class path to resolve the json but when it has to resolve the class of the verticle it's using the default class path.

Originally opened: here https://github.com/vert-x3/vertx-web/issues/1290

**Comment by msillence** [comment]
Ahh, that's embarrassing, I copied an example json that overwrote the isolation group sorry.
It in fact with the correct deployment json it works fine...

**Comment by tsegismont** [comment]
Thanks for letting us know.
