### ISSUE TITLE
Service verticle factory does not respect "worker=true" setting

### ISSUE THREAD

**Issue by jgarcia241** [vert-x3/vertx-service-factory#13]
Version 4.0

I deploy most of the vertices as services with a json service descriptor.
When moving from 3.x to 4 I noticed that services that are marked as 'worker:true' are not being deployed as worker vertices and are executed in a even loop thread.

How to reproduce:

1.- Deploy any service verticle as a worker verticle (worker:true in the json descriptor in the 'options' section)
2.- The easiest way to verify if it is a worker verticle is to log something and check the thread name. Otherwise, you can use VertxThread.isWorker()

Seems to be an issue with the code in the service Factory, when it merges the config from the context.

**Comment by vietj** [comment]
https://github.com/vert-x3/vertx-service-factory/issues/14
