### ISSUE TITLE
service descriptor json file naming documentation for maven

### ISSUE THREAD

**Issue by ghost** [vert-x3/vertx-service-factory#3]
Maybe the vertx-service-factory docs could stress more that the name really matters for vertx-maven-service-factory use? To be fair, the [service identifier section](https://github.com/vert-x3/vertx-service-factory#service-identifier) already clearly mentions the correspondence to maven coords, but maybe that section and/or the service descriptor section could make it a bit more explicit.  Maybe to steer people in the right direction [service descriptor section](https://github.com/vert-x3/vertx-service-factory#service-descriptor) could be amended along the lines of:

> E.g. For a service with a service owner (maven groupId) of `com.mycompany.clever`, a service name (maven artifactId) of `clever-db-service`, and a version of `1.0`, the corresponding service descriptor json file would be called: `com.mycompany.clever.clever-db-service.1.0.json`

**Comment by purplefox** [comment]
Done
