### ISSUE TITLE
Add instructions about fat jar in the manual

### ISSUE THREAD

**Issue by cescoffier** [vert-x3/vertx-service-factory#8]
We need to extend the manual to explain how you can deploy services when using a fat-jar

**Comment by Spotback** [comment]
Any updates on this. i am having a problem with running a fat jar with https. i have my app that runs fine in my ide, but never launches as a fat jar. Ive cloned the vertx docker fat jar repo and it runs fine with the hello world example. i copied my createHttpServer code using ssl  and it never starts the server
`HttpServer server = vertx.createHttpServer(new HttpServerOptions().setSsl(true).setKeyStoreOptions(
      new JksOptions().setPath("/server-keystore.jks").setPassword("wibble")
    ));
    server.requestHandler(req -> {
      req.response().end("hello");
    }).listen(8880`

**Comment by vietj** [comment]
it's not clear what you are doing, this repository is about the vertx service factory. perhaps you can look in vertx examples https://github.com/vert-x3/vertx-examples/tree/master/fatjar-examples here there are a few examples
